### ISSUE TITLE
No module named 'scripts.cli'

### ISSUE THREAD

**Issue by qweasdzxc110** [scherroman/mugen#20]
(base) abcdeMacBook-Pro:mugen abc$ mugen
Traceback (most recent call last):
  File "/Users/abc/anaconda3/bin/mugen", line 11, in <module>
    load_entry_point('mugen', 'console_scripts', 'mugen')()
  File "/Users/abc/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/abc/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/Users/abc/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/Users/abc/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'scripts.cli'

**Comment by scherroman** [comment]
Hey qweasdzxc110, its been quite a while but it looks like you were using python 3.5 here. The minimum python version supported by the project was 3.6, and is now 3.7, so if you still want to try after all this time try with python 3.7!

**Comment by wanghaisheng** [comment]
$ python -V
Python 3.8.5
(base) 
dubo@LAPTOP-I2R9VG58 MINGW64 /d/Download/audio-visual/UCBBj-A2EqL5pNApsLhoeM6w
$ mugen
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\Scripts\mugen-script.py", line 33, in <module>
    sys.exit(load_entry_point('mugen', 'console_scripts', 'mugen')())
  File "D:\Program Files\anaconda3\Scripts\mugen-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\Program Files\anaconda3\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\Program Files\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scripts.cli'
(base)

**Comment by scherroman** [comment]
@wanghaisheng if you're still interested, try downloading and installing the project from scratch once more. I've made some updates that should fix using mugen on Windows, along with continuous integration to test the project across platforms when new updates are merged.
